# scripts/filters/armor.py
# Daftar nama armor (termasuk helm, cuirass, boots, gauntlets, shield) Skyrim

ARMOR_NAMES = [
    # Light Armor Sets
    "Ancient Falmer Armor",
    "Ancient Shrouded Armor",
    "Armor of the Old Gods",
    "Blackguard's Armor",
    "Chitin Armor",
    "Dawnguard Armor",
    "Deathbrand Armor",
    "Dragonscale Armor",
    "Elven Armor",
    "Fur Armor",
    "Glass Armor",
    "Guild Master's Armor Set",
    "Hide Armor",
    "Imperial Light Armor",
    "Leather Armor",
    "Linwe's Armor Set",
    "Morag Tong Armor",
    "Nightingale Armor",
    "Penitus Oculatus Armor",
    "Scaled Armor",
    "Shrouded Armor",
    "Skaal Armor",
    "Stalhrim Light Armor",
    "Stormcloak Armor",
    "Stormcloak Officer Armor",
    "Thieves Guild Armor",
    "Worn Shrouded Armor",
    # Heavy Armor Sets
    "Ancient Nord Armor",
    "Ahzidal's Armor",
    "Blades Armor",
    "Bonemold Armor",
    "Chitin Heavy Armor",
    "Daedric Armor",
    "Dawnguard Heavy Armor",
    "Dragonplate Armor",
    "Dwarven Armor",
    "Ebony Armor",
    "Falmer Armor",
    "Falmer Heavy Armor",
    "Falmer Hardened Armor",
    "Imperial Armor",
    "Iron Armor",
    "Nordic Carved Armor",
    "Orcish Armor",
    "Stalhrim Armor",
    "Steel Armor",
    "Steel Plate Armor",
    "Wolf Armor",
    # Headgear Light
    "Ancient Shrouded Cowl",
    "Blackguard's Hood",
    "Chitin Helmet",
    "Dawnguard Helmet",
    "Deathbrand Helm",
    "Dragonscale Helmet",
    "Elven Helmet",
    "Elven Light Helmet",
    "Falkreath Guard's Helmet",
    "Forsworn Headdress",
    "Fur Helmet",
    "Glass Helmet",
    "Guild Master's Hood",
    "Helmet of the Old Gods",
    "Hide Helmet",
    "Hjaalmarch Guard's Helmet",
    "Imperial Light Helmet",
    "Krosis",
    "Leather Helmet",
    "Linwe's Hood",
    "Markarth Guard's Helmet",
    "Miraak",
    "Morag Tong Hood",
    "Morokei",
    "Nightingale Hood",
    "Noster's Helmet",
    "Pale Guard's Helmet",
    "Penitus Oculatus Helmet",
    "Riften Guard's Helmet",
    "Scaled Helmet",
    "Shrouded Cowl",
    "Shrouded Cowl Maskless",
    "Solitude Guard's Helmet",
    "Skaal Hat",
    "Stalhrim Light Helmet",
    "Stormcloak Helmet",
    "Stormcloak Officer Helmet",
    "Thieves Guild Hood",
    "Torturer's Hood",
    "Volsung",
    "Winterhold Guard's Helmet",
    "Whiterun Guard's Helmet",
    "Wooden Mask",
    "Worn Shrouded Cowl",
    # Headgear Heavy
    "Ahzidal",
    "Ahzidal's Helm of Vision",
    "Ancient Helmet of the Unburned",
    "Ancient Nord Helmet",
    "Blades Helmet",
    "Bonemold Helmet",
    "Chitin Heavy Helmet",
    "Cultist Mask",
    "Daedric Helmet",
    "Dawnguard Full Helmet",
    "Dragonplate Helmet",
    "Dukaan",
    "Dwarven Helmet",
    "Ebony Helmet",
    "Falmer Hardened Helm",
    "Falmer Heavy Helm",
    "Falmer Helmet",
    "Helm of Yngol",
    "Helm of Winterhold",
    "Hevnoraak",
    "Imperial Helmet",
    "Imperial Helmet (Closed)",
    "Imperial Officer's Helmet",
    "Improved Bonemold Helmet",
    "Iron Helmet",
    "The Jagged Crown",
    "Konahrik",
    "Masque of Clavicus Vile",
    "Nahkriin",
    "Nordic Carved Helmet",
    "Orcish Helmet",
    "Otar",
    "Rahgot",
    "Shellbug Helmet",
    "Stalhrim Helm",
    "Steel Helmet",
    "Steel Horned Helmet",
    "Steel Plate Helmet",
    "Visage of Mzund",
    "Vokun",
    "Wolf Helmet",
    "Zahkriisos",
    # Cuirasses Light
    "Ancient Falmer Cuirass",
    "Elven Gilded Armor",
    "Elven Light Armor",
    "Falkreath Guard's Armor",
    "Forsworn Armor",
    "Guild Master's Armor",
    "Hide Armor",
    "Hjaalmarch Guard's Armor",
    "Linwe's Armor",
    "Leather Armor",
    "Markarth Guard's Armor",
    "Pale Guard's Armor",
    "Riften Guard's Armor",
    "Savior's Hide",
    "Scaled Horn Armor",
    "Skaal Coat",
    "Solitude Guard's Armor",
    "Stormcloak Cuirass",
    "Studded Armor",
    "Studded Imperial Armor",
    "Vampire Armor",
    "Vampire Royal Armor",
    "Whiterun Guard's Armor",
    "Winterhold Guard's Armor",
    # Cuirasses Heavy
    "Ahzidal's Armor of Retribution",
    "Banded Iron Armor",
    "Bonemold Guard Armor",
    "Bonemold Pauldron Armor",
    "Ebony Mail",
    "General Tullius' Armor",
    "Improved Bonemold Armor",
    "Wolf Armor",
    # Boots Light
    "Ancient Falmer Boots",
    "Ancient Shrouded Boots",
    "Blackguard's Boots",
    "Boots of the Old Gods",
    "Chitin Boots",
    "Dawnguard Boots",
    "Deathbrand Boots",
    "Dragonscale Boots",
    "Elven Boots",
    "Elven Light Boots",
    "Forsworn Boots",
    "Fur Boots",
    "Fur Shoes",
    "Glass Boots",
    "Guild Master's Boots",
    "Hide Boots",
    "Imperial Light Boots",
    "Linwe's Boots",
    "Leather Boots",
    "Miraak's Boots",
    "Morag Tong Boots",
    "Movarth's Boots",
    "Nightingale Boots",
    "Penitus Oculatus Boots",
    "Predator's Grace",
    "Scaled Boots",
    "Shrouded Boots",
    "Skaal Boots",
    "Stalhrim Light Boots",
    "Stormcloak Officer Boots",
    "Thieves Guild Boots",
    "Vampire Boots",
    "Worn Shrouded Boots",
    # Boots Heavy
    "Ahzidal's Boots of Waterwalking",
    "Ancient Nord Boots",
    "Blades Boots",
    "Bonemold Boots",
    "Chitin Heavy Boots",
    "Daedric Boots",
    "Dawnguard Heavy Boots",
    "Dragonplate Boots",
    "Dwarven Boots",
    "Ebony Boots",
    "Falmer Boots",
    "Falmer Hardened Boots",
    "Falmer Heavy Boots",
    "Imperial Boots",
    "Improved Bonemold Boots",
    "Iron Boots",
    "Nordic Carved Boots",
    "Orcish Boots",
    "Stalhrim Boots",
    "Steel Shin Boots",
    "Steel Cuffed Boots",
    "Steel Plate Boots",
    "Wolf Boots",
    # Gauntlets Light
    "Ancient Falmer Gauntlets",
    "Ancient Shrouded Gloves",
    "Blackguard's Gloves",
    "Chitin Bracers",
    "Cultist Gloves",
    "Dawnguard Gauntlets",
    "Deathbrand Gauntlets",
    "Dragonscale Gauntlets",
    "Elven Gauntlets",
    "Elven Light Gauntlets",
    "Forsworn Gauntlets",
    "Fur Bracers",
    "Fur Gauntlets",
    "Gauntlets of the Old Gods",
    "Gilded Wristguards",
    "Glass Gauntlets",
    "Gloves of the Pugilist",
    "Guild Master's Gloves",
    "Hide Bracers",
    "Imperial Light Bracers",
    "Leather Bracers",
    "Linwe's Gloves",
    "Miraak's Gloves",
    "Morag Tong Bracers",
    "Nightingale Gloves",
    "Penitus Oculatus Bracers",
    "Scaled Bracers",
    "Shrouded Gloves",
    "Skaal Gloves",
    "Stalhrim Light Bracers",
    "Stormcloak Officer Bracers",
    "Thieves Guild Gloves",
    "Tumblerbane Gloves",
    "Ulfric's Bracers",
    "Vampire Gauntlets",
    "Worn Shrouded Gloves",
    # Gauntlets Heavy
    "Ahzidal's Gauntlets of Warding",
    "Ancient Nord Gauntlets",
    "Blades Gauntlets",
    "Bonemold Gauntlets",
    "Chitin Heavy Gauntlets",
    "Daedric Gauntlets",
    "Dawnguard Heavy Gauntlets",
    "Dragonplate Gauntlets",
    "Dwarven Gauntlets",
    "Ebony Gauntlets",
    "Falmer Gauntlets",
    "Falmer Hardened Gauntlets",
    "Falmer Heavy Gauntlets",
    "Imperial Bracers",
    "Improved Bonemold Gauntlets",
    "Iron Gauntlets",
    "Ironhand Gauntlets",
    "Nordic Carved Gauntlets",
    "Orcish Gauntlets",
    "Stalhrim Gauntlets",
    "Steel Imperial Gauntlets",
    "Steel Nordic Gauntlets",
    "Steel Plate Gauntlets",
    "The Forgemaster's Fingers",
    "Wolf Gauntlets",
    # Shields Light
    "Amber Shield",
    "Chitin Shield",
    "Dark Seducer Shield",
    "Dragonscale Shield",
    "Elven Shield",
    "Glass Shield",
    "Hide Shield",
    "Imperial Light Shield",
    "Netch Leather Shield",
    "Netch Leather Tower Shield",
    "Remnant Shield",
    "Shadowed Netch Leather Shield",
    "Shadowed Netch Leather Tower Shield",
    "Stalhrim Shield",
    # Shields Heavy
    "Banded Iron Shield",
    "Blades Ebony Shield",
    "Blades Shield",
    "Bonemold Shield",
    "Daedric Shield",
    "Dawnguard Shield",
    "Dented Iron Shield",
    "Dragonplate Shield",
    "Dwarven Shield",
    "Ebony Shield",
    "Falmer Shield",
    "Golden Saint Shield",
    "Hrolfdir's Shield",
    "Imperial Dragon Shield",
    "Imperial Shield",
    "Improved Bonemold Shield",
    "Iron Shield",
    "Madness Shield",
    "Nordic Shield",
    "Orcish Shield",
    "Ordinator Shield",
    "Roggi's Ancestral Shield",
    "Skull-Sabre Shield",
    "Steel Shield",
    # Jewelry with armor (some unique items)
    "Amulet of Articulation",
    "Diadem of the Savant",
    "Locket of Saint Jiub",
]