# scripts/filters/books.py
# Daftar nama buku (books) Skyrim – termasuk lore books, skill books, quest books, dll.

BOOK_NAMES = [
    "16 Accords of Madness, v. VI",
    "16 Accords of Madness, v. IX",
    "Sixteen Accords of Madness, Book XII",
    "2920, vol 01 - Morning Star",
    "2920, vol 02 - Sun's Dawn",
    "2920, vol 03 - First Seed",
    "2920, vol 04 - Rain's Hand",
    "2920, vol 05 - Second Seed",
    "2920, vol 06 - Mid Year",
    "2920, vol 07 - Sun's Height",
    "2920, vol 08 - Last Seed",
    "2920, vol 09 - Hearth Fire",
    "2920, vol 10 - Frostfall",
    "2920, vol 11 - Sun's Dusk",
    "2920, vol 12 - Evening Star",
    "A Children's Anuad",
    "A Dance in Fire, Book I",
    "A Dance in Fire, Book II",
    "A Dance in Fire, Book III",
    "A Dance in Fire, Book IV",
    "A Dance in Fire, Book V",
    "A Dance in Fire, Book VI",
    "A Dance in Fire, Book VII",
    "A Dream of Sovngarde",
    "A Game at Dinner",
    "A Gentleman's Guide to Whiterun",
    "A Hypothetical Treachery",
    "A Kiss, Sweet Mother",
    "A Minor Maze",
    "A Tragedy in Black",
    "Adonato's Book",
    "Advances in Lockpicking",
    "Aedra and Daedra",
    "Aevar Stone-Singer",
    "Ahzidal's Descent",
    "Ahzirr Traajijazeri",
    "Alduin is Real",
    "Amongst the Draugr",
    "An Accounting of the Scrolls",
    "An Explorer's Guide to Skyrim",
    "Ancestors and the Dunmer",
    "Annals of the Dragonguard",
    "Antecedents of Dwemer Law",
    "Arcana Restored",
    "Atlas of Dragons",
    "Azura and the Box",
    "Battle of Sancre Tor",
    "Before the Ages of Man",
    "Beggar",
    "Beggar Prince",
    "Biography of Barenziah, v1",
    "Biography of Barenziah, v2",
    "Biography of Barenziah, v3",
    "Biography of the Wolf Queen",
    "Black Book: Epistolary Acumen",
    "Black Book: Filament and Filigree",
    "Black Book: The Hidden Twilight",
    "Black Book: The Sallow Regent",
    "Black Book: The Winds of Change",
    "Black Book: Untold Legends",
    "Black Book: Waking Dreams",
    "Boethiah's Glory",
    "Boethiah's Proving",
    "Bone, Part I",
    "Bone, Part II",
    "Breathing Water",
    "Brief History of the Empire, v1",
    "Brief History of the Empire, v2",
    "Brief History of the Empire, v3",
    "Brief History of the Empire, v4",
    "Brothers of Darkness",
    "Catalogue of Armor Enchantments",
    "Catalogue of Weapon Enchantments",
    "Cats of Skyrim",
    "Chance's Folly",
    "Changed Ones",
    "Charwich-Koniinge Letters, v1",
    "Charwich-Koniinge Letters, v2",
    "Charwich-Koniinge Letters, v3",
    "Charwich-Koniinge Letters, v4",
    "Chaurus Pie: A Recipe",
    "Cherim's Heart",
    "Children of the All-Maker",
    "Children of the Sky",
    "Chimarvamidium",
    "Chronicles of Nchuleft",
    "Cleansing of the Fane",
    "Confessions of a Dunmer Skooma Eater",
    "Confessions of a Khajiit Fur Trader",
    "Consider Adoption",
    "Darkest Darkness",
    "Daughter of the Niben",
    "De Rerum Dirennis",
    "Death Blow of Abernanit",
    "Death of a Wanderer",
    "Deathbrand",
    "Diary of Faire Agarwen",
    "Dragon Language: Myth no More",
    "Dunmer of Skyrim",
    "Dwarves, v1",
    "Dwarves, v2",
    "Dwarves, v3",
    "Dwemer History and Culture",
    "Dwemer Inquiries Vol I",
    "Dwemer Inquiries Vol II",
    "Dwemer Inquiries Vol III",
    "Effects of the Elder Scrolls",
    "Enchanter's Primer",
    "Fall From Glory",
    "Fall of the Snow Prince",
    "Father Of The Niben",
    "Feyfolken, Book I",
    "Feyfolken, Book II",
    "Feyfolken, Book III",
    "Final Lesson",
    "Fire and Darkness",
    "Five Songs of King Wulfharth",
    "Flight from the Thalmor",
    "Forge, Hammer and Anvil",
    "Fragment: On Artaeum",
    "Frontier, Conquest",
    "Galerion the Mystic",
    "Ghosts in the Storm",
    "Glories and Laments",
    "Gods and Worship",
    "Great Harbingers",
    "Guide to Better Thieving",
    "Hallgerd's Tale",
    "Hanging Gardens",
    "Harvesting Frostbite Spider Venom",
    "Heavy Armor Forging",
    "Herbalist's Guide to Skyrim",
    "Herbane's Bestiary: Automatons",
    "Herbane's Bestiary: Hagravens",
    "Herbane's Bestiary: Ice Wraiths",
    "History of Raven Rock, Vol. I",
    "History of Raven Rock, Vol. II",
    "History of Raven Rock, Vol. III",
    "Holdings of Jarl Gjalund",
    "Horker Attacks",
    "Horror of Castle Xyr",
    "Ice and Chitin",
    "Immortal Blood",
    "Imperial Report on Saarthal",
    "Incident at Necrom",
    "Invocation of Azura",
    "Jornibret's Last Dance",
    "Journal of Mirtil Angoth",
    "Killing - Before You're Killed",
    "King",
    "King Olaf's Verse",
    "Kolb and the Dragon",
    "Lakeview Manor Charter",
    "Last Scabbard of Akrash",
    "Legend of Krately House",
    "Letter from the Jarl of Falkreath",
    "Letter from the Steward of Falkreath",
    "Life of Uriel Septim VII",
    "Light Armor Forging",
    "Liminal Bridges",
    "Lives of the Saints",
    "Lost Legends",
    "Lycanthropic Legends of Skyrim",
    "Mace Etiquette",
    "Magic from the Sky",
    "Malyn Varen's Grimoire",
    "Mannimarco, King of Worms",
    "Markarth Home Decorating Guide",
    "Mixed Unit Tactics v1",
    "Mysterious Akavir",
    "Mystery of Talara, v 1",
    "Mystery of Talara, v 2",
    "Mystery of Talara, v 3",
    "Mystery of Talara, v 4",
    "Mystery of Talara, v 5",
    "Mythic Dawn Commentaries 1",
    "Mythic Dawn Commentaries 2",
    "Mythic Dawn Commentaries 3",
    "Mythic Dawn Commentaries 4",
    "Myths of Sheogorath",
    "N'Gasta! Kvata! Kvakis!",
    "Nchunak's Fire and Faith",
    "Nerevar at Red Mountain",
    "Nerevar Moon and Star",
    "Night of Tears",
    "Night Falls on Sentinel",
    "Nightingales: Fact or Fiction?",
    "Nords Arise!",
    "Nords of Skyrim",
    "Notes on Dimhollow Crypt, Vol. 3",
    "Notes on the Lunar Forge",
    "Notes on Yngol Barrow",
    "Ode To The Tundrastriders",
    "Of Crossed Daggers",
    "Of Fjori and Holgeir",
    "Oghma Infinium",
    "Olaf and the Dragon",
    "On Apocrypha: Boneless Limbs",
    "On Apocrypha: Delving Pincers",
    "On Apocrypha: Gnashing Blades",
    "On Apocrypha: Prying Orbs",
    "On Oblivion",
    "On Stepping Lightly",
    "On the Great Collapse",
    "Opusculus Lamae Bal",
    "Orsinium and the Orcs",
    "Palla, Book I",
    "Palla, Book II",
    "Pension of the Ancestor Moth",
    "Physicalities of Werewolves",
    "Pirate King of the Abecean",
    "Power of the Elements",
    "Proper Lock Design",
    "Purloined Shadows",
    "Racial Phylogeny",
    "Reality & Other Falsehoods",
    "Remanada",
    "Report: Disaster at Ionith",
    "Response to Bero's Speech",
    "Riften Home Decorating Guide",
    "Rising Threat, Vol. I",
    "Rising Threat, Vol. II",
    "Rising Threat, Vol. III",
    "Rising Threat, Vol. IV",
    "Rislav The Righteous",
    "Ruins of Kemel-Ze",
    "Rumination on the Elder Scrolls",
    "Sacred Witness",
    "Saint Jiub's Opus",
    "Scourge of the Gray Quarter",
    "Shadowmarks",
    "Shezarr and the Divines",
    "Short History of Morrowind",
    "Sithis",
    "Skyrim's Rule",
    "Solitude Home Decorating Guide",
    "Song of Hrormir",
    "Song of the Alchemists",
    "Song of the Askelde Men",
    "Songs of Skyrim",
    "Songs of Skyrim: Revised",
    "Songs of the Return, Vol 2",
    "Songs of the Return, Vol 7",
    "Songs of the Return, Vol 19",
    "Songs of the Return, Vol 24",
    "Songs of the Return, Vol 56",
    "Souls, Black and White",
    "Sovngarde, a Reexamination",
    "Spirit of Nirn",
    "Spirit of the Daedra",
    "Surfeit of Thieves",
    "The Adabal-a",
    "The Aetherium Wars",
    "The Alduin-Akatosh Dichotomy",
    "The Amulet of Kings",
    "The Anticipations",
    "The Apprentice's Assistant",
    "The Arcturian Heresy",
    "The Argonian Account, Book I",
    "The Argonian Account, Book II",
    "The Argonian Account, Book III",
    "The Argonian Account, Book IV",
    "The Armorer's Challenge",
    "The Art of War Magic",
    "The Axe Man",
    "The Battle of Red Mountain",
    "The Bear of Markarth",
    "The Beginner's Guide to Homesteading",
    "The Betrayed",
    "The Black Arrow, v1",
    "The Black Arrow, v2",
    "The Black Arts On Trial",
    "The Book of Daedra",
    "The Book of Fate",
    "The Book of Life and Service",
    "The Book of the Dragonborn",
    "The Buying Game",
    "The Cabin in the Woods",
    "The Cake and the Diamond",
    "The City of Stone",
    "The Code of Malacath",
    "The Doors of Oblivion",
    "The Doors of the Spirit",
    "The Dowry",
    "The Dragon Break",
    "The Dragon War",
    "The Dreamstride",
    "The Exodus",
    "The Falmer: A Study",
    "The Firmament",
    "The Firsthold Revolt",
    "The Five Far Stars",
    "The Four Totems of Volskygge",
    "The Gold Ribbon of Merit",
    "The Great War",
    "The Guardian and the Traitor",
    "The Holds of Skyrim",
    "The Hope of the Redoran",
    "The House of Troubles",
    "The Importance of Where",
    "The Knights of the Nine",
    "The Last King of the Ayleids",
    "The Legend of Red Eagle",
    "The Legendary Sancre Tor",
    "The Legendary Scourge",
    "The Locked Room",
    "The Lunar Lorkhan",
    "The Lusty Argonian Maid Vol 1",
    "The Lusty Argonian Maid Vol 2",
    "The Madmen of the Reach",
    "The Madness of Pelagius",
    "The Marksmanship Lesson",
    "The Mirror",
    "The Monomyth",
    "The Night Mother's Truth",
    "The Nightingales Vol. 1",
    "The Nightingales Vol. 2",
    "The Nirnoot Missive",
    "The Oblivion Crisis",
    "The Old Ways",
    "The Pig Children",
    "The Poison Song, Book I",
    "The Poison Song, Book II",
    "The Poison Song, Book III",
    "The Poison Song, Book IV",
    "The Poison Song, Book V",
    "The Poison Song, Book VI",
    "The Poison Song, Book VII",
    "The Posting of the Hunt",
    "The Ransom of Zarek",
    "The Real Barenziah, Book I",
    "The Real Barenziah, Book II",
    "The Real Barenziah, Book III",
    "The Real Barenziah, Book IV",
    "The Real Barenziah, Book V",
    "The Rear Guard",
    "The Reclamations",
    "The Red Book of Riddles",
    "The Red Kitchen Reader",
    "The Red Year, Vol I",
    "The Red Year, Vol II",
    "The Refugees",
    "The Rise and Fall of the Blades",
    "The Secrets of Ragnvald",
    "The Seed",
    "The Song of Pelinal, Book I",
    "The Song of Pelinal, Book II",
    "The Song of Pelinal, Book III",
    "The Song of Pelinal, Book IV",
    "The Song of Pelinal, Book V",
    "The Song of Pelinal, Book VI",
    "The Song of Pelinal, Book VII",
    "The Song of Pelinal, Book VIII",
    "The Sultry Argonian Bard, v1",
    "The Tale of Dro'Zira",
    "The Talos Mistake",
    "The Third Door",
    "The Third Era Timeline",
    "The Totems of Hircine",
    "The True Nature of Orcs",
    "The True Noble's Code",
    "The Warrior's Charge",
    "The Waters of Oblivion",
    "The Wild Elves",
    "The Windhelm Letters",
    "The Wispmother",
    "The Wolf Queen, Book I",
    "The Wolf Queen, Book II",
    "The Wolf Queen, Book III",
    "The Wolf Queen, Book IV",
    "The Wolf Queen, Book V",
    "The Wolf Queen, Book VI",
    "The Wolf Queen, Book VII",
    "The Wolf Queen, Book VIII",
    "The Woodcutter's Wife",
    "There Be Dragons",
    "Thief",
    "Thief of Virtue",
    "Thirsk, a Revised History",
    "Treatise on Ayleidic Cities",
    "Three Thieves",
    "Trap",
    "Trials of St. Alessia",
    "Troll Slaying",
    "Touching the Sky",
    "Twin Secrets",
    "Ulfr's Book",
    "Uncommon Taste",
    "Uncommon Taste - Signed",
    "Unknown Book, Vol. I",
    "Unknown Book, Vol. II",
    "Unknown Book, Vol. III",
    "Unknown Book, Vol. IV",
    "Varieties of Daedra",
    "Varieties of Faith in the Empire",
    "Vernaccus and Bourlor",
    "Wabbajack",
    "Walking the World, Vol XI",
    "War of the First Council",
    "Warrior",
    "Watcher of Stones",
    "Where were you when the Dragon Broke?",
    "Whiterun Home Decorating Guide",
    "Withershins",
    "Wind and Sand",
    "Windhelm Home Decorating Guide",
    "Words and Philosophy",
    "Words of Clan Mother Ahnissi",
    "Words of the Wind",
    "Wraith's Wedding Dowry",
    "Yellow Book of Riddles",
    "Yngol And The Sea-Ghosts",
]