# scripts/filters/clothing.py
# Daftar nama pakaian (clothing) Skyrim – termasuk robes, headwear, gloves, footwear, unique

CLOTHING_NAMES = [
    # Upper/Lower body
    "Arm Bandages",
    "Belted Tunic",
    "Blacksmith's Apron",
    "Chef's Tunic",
    "Child's Clothes",
    "Clothes",
    "Dunmer Outfit",
    "Embellished Robes",
    "Embroidered Garments",
    "Fine Clothes",
    "Fine Raiment",
    "Fur-Trimmed Cloak",
    "Hammerfell Garb",
    "Miner's Clothes",
    "Mourner's Clothes",
    "Noble Clothes",
    "Radiant Raiment Fine Clothes",
    "Ragged Robes",
    "Ragged Trousers",
    "Redguard Clothes",
    "Refined Tunic",
    "Roughspun Tunic",
    "Tavern Clothes",
    "Vampire Robes",
    # Robes
    "Black Robes",
    "Blue Robes",
    "College Robes",
    "Green Robes",
    "Grey Robes",
    "Greybeard's Robe",
    "Hooded Black Robes",
    "Hooded Monk Robes",
    "Mage Robes",
    "Monk Robes",
    "Psiijic Robes",
    "Vaermina Robes",
    "Red Robes",
    # Headwear
    "Alik'r Hood",
    "Chef's Hat",
    "Cowl",
    "Fine Hat",
    "Hat",
    "Mage Hood",
    "Mourner's Hat",
    "Psiijic Hood",
    "Ragged Cap",
    "Redguard Hood",
    "Temple Priest Hood",
    "Vampire Hood",
    # Gloves
    "Gloves",
    "Mystic Tuning Gloves",
    "Mythic Dawn Gloves",
    "Prisoner's Cuffs",
    "Psiijic Gloves",
    "Thalmor Gloves",
    "Vampire Gloves",
    # Footwear
    "Boots",
    "College Boots",
    "Cuffed Boots",
    "Cultist Boots",
    "Dunmer Shoes",
    "Fine Boots",
    "Footwraps",
    "Fur-Lined Boots",
    "Mythic Dawn Boots",
    "Pleated Shoes",
    "Psiijic Boots",
    "Ragged Boots",
    "Redguard Boots",
    "Shoes",
    "Temple Priest Boots",
    "Thalmor Boots",
    "Vampire Boots",
    # Unique clothing
    "Emperor's Robes",
    "Mythic Dawn Robes",
    "Nocturnal's Clothes",
    "Party Boots",
    "Party Clothes",
    "Red Hooded Robes",
    "Sheogorath Outfit",
    "Ulfric's Clothes",
    "Ulfric's Boots",
    "Ulfric's Bracers",
    "Wedding Dress",
    "Wedding Wreath",
    "Wedding Sandals",
]