# scripts/filters/items.py
# Daftar nama senjata (weapons) Skyrim – digunakan untuk filter dan proteksi proper noun

ITEM_NAMES = [
    # Daggers
    "Alessandra's Dagger",
    "Blade of Sacrifice",
    "Blade of Woe",
    "Bloodthorn",
    "Borvir's Dagger",
    "Daedric Dagger",
    "Dragon Priest Dagger",
    "Dragonbone Dagger",
    "Dwarven Dagger",
    "Ebony Dagger",
    "Elven Dagger",
    "Glass Dagger",
    "Iron Dagger",
    "Kahvozein's Fang",
    "Keening",
    "Mehrunes' Razor",
    "Nettlebane",
    "Nordic Dagger",
    "Orcish Dagger",
    "Rundi's Dagger",
    "Shiv",
    "Skyforge Steel Dagger",
    "Stalhrim Dagger",
    "Steel Dagger",
    "Valdr's Lucky Dagger",
    # Maces
    "Daedric Mace",
    "Dragonbone Mace",
    "Dwarven Mace",
    "Ebony Mace",
    "Elven Mace",
    "Glass Mace",
    "Horksbane",
    "Iron Mace",
    "Lunar Iron Mace",
    "Lunar Steel Mace",
    "Mace of Molag Bal",
    "Nordic Mace",
    "Orcish Mace",
    "Prelate's Mace",
    "Rusty Mace",
    "Stalhrim Mace",
    "Steel Mace",
    # Swords
    "Akaviri Sword",
    "Amren's Family Sword",
    "Ancient Nord Sword",
    "Blades Sword",
    "Bloodscythe",
    "Bolar's Oathblade",
    "Ceremonial Sword",
    "Chillrend",
    "Daedric Sword",
    "Dawnbreaker",
    "Dragonbane",
    "Dragonbone Sword",
    "Drainheart Sword",
    "Dwarven Sword",
    "Ebony Sword",
    "Eduj",
    "Elven Sword",
    "Falmer Sword",
    "Forsworn Sword",
    "Gauldur Blackblade",
    "Ghostblade",
    "Glass Sword",
    "Grimsever",
    "Harkon's Sword",
    "Herebane's Courage",
    "Hjalti's Sword",
    "Honed Ancient Nord Sword",
    "Honed Falmer Sword",
    "Imperial Sword",
    "Iron Sword",
    "Lunar Iron Sword",
    "Lunar Steel Sword",
    "Miraak's Sword",
    "Nightingale Blade",
    "Nord Hero Sword",
    "Nordic Sword",
    "Orcish Sword",
    "Phantom Sword",
    "Queen Freydis's Sword",
    "Red Eagle's Bane",
    "Red Eagle's Fury",
    "Scimitar",
    "Silver Sword",
    "Skyforge Steel Sword",
    "Stalhrim Sword",
    "Steel Sword",
    "Soulrender",
    "The Pale Blade",
    "Vilkas's Sword",
    "Windshear",
    "Wooden Sword",
    # War Axes
    "Ancient Nord War Axe",
    "Ancient Nordic Pickaxe",
    "Balgruuf's War Axe",
    "Ceremonial Axe",
    "Daedric War Axe",
    "Dawnguard Rune Axe",
    "Dawnguard War Axe",
    "Dragonbone War Axe",
    "Dwarven War Axe",
    "Ebony War Axe",
    "Elven War Axe",
    "Falmer War Axe",
    "Forsworn Axe",
    "Ghorbash's Ancestral Axe",
    "Glass War Axe",
    "Hoarfrost",
    "Honed Draugr War Axe",
    "Honed Falmer War Axe",
    "Illusory War Axe",
    "Iron War Axe",
    "Lunar Iron War Axe",
    "Lunar Steel War Axe",
    "Nord Hero War Axe",
    "Nordic War Axe",
    "Notched Pickaxe",
    "Okin",
    "Orcish War Axe",
    "Pickaxe",
    "Poacher's Axe",
    "Skyforge Steel War Axe",
    "Stalhrim War Axe",
    "Steel War Axe",
    "Ulfric's War Axe",
    "Woodcutter's Axe",
    # Other one-handed
    "Fork",
    "Knife",
    # Battleaxes (two-handed)
    "Ancient Nord Battle Axe",
    "Daedric Battleaxe",
    "Dragonbone Battleaxe",
    "Drainblood Battleaxe",
    "Dwarven Battleaxe",
    "Ebony Battleaxe",
    "Elven Battleaxe",
    "Glass Battleaxe",
    "Headsman's Axe",
    "Honed Ancient Nord Battle Axe",
    "Iron Battleaxe",
    "Nord Hero Battle Axe",
    "Nordic Battleaxe",
    "Orcish Battleaxe",
    "Skyforge Steel Battleaxe",
    "Stalhrim Battleaxe",
    "Steel Battleaxe of Fiery Souls",
    "Steel Battleaxe",
    "Rueful Axe",
    "The Woodsman's Friend",
    "Tsun's Battleaxe",
    "Wuuthrad",
    # Greatswords
    "Ancient Nord Greatsword",
    "Balgruuf's Greatsword",
    "Bloodskal Blade",
    "Daedric Greatsword",
    "Dragonbone Greatsword",
    "Dwarven Greatsword",
    "Ebony Greatsword",
    "Ebony Blade",
    "Elven Greatsword",
    "Glass Greatsword",
    "Honed Ancient Nord Greatsword",
    "Iron Greatsword",
    "Nord Hero Greatsword",
    "Nordic Greatsword",
    "Orcish Greatsword",
    "Silver Greatsword",
    "Skyforge Steel Greatsword",
    "Stalhrim Greatsword",
    "Steel Greatsword",
    "Stormfang",
    # Warhammers
    "Aegisbane",
    "Champion's Cudgel",
    "Daedric Warhammer",
    "Dawnguard Warhammer",
    "Dawnguard Rune Hammer",
    "Dragonbone Warhammer",
    "Dwarven Warhammer",
    "Ebony Warhammer",
    "Elven Warhammer",
    "Glass Warhammer",
    "Iron Warhammer",
    "Nordic Warhammer",
    "Orcish Warhammer",
    "Shagrol's Warhammer",
    "Stalhrim Warhammer",
    "Steel Warhammer",
    "The Longhammer",
    "Trollsbane",
    "Volendrung",
    # Bows
    "Ancient Nord Bow",
    "Angi's Bow",
    "Auriel's Bow",
    "Bow of Shadows",
    "Bow of the Hunt",
    "Daedric Bow",
    "Dragonbone Bow",
    "Drainspell Bow",
    "Draven's Bow",
    "Dwarven Bow",
    "Dwarven Black Bow of Fate",
    "Ebony Bow",
    "Elven Bow",
    "Falmer Bow",
    "Falmer Supple Bow",
    "Firiniel's End",
    "Forsworn Bow",
    "Froki's Bow",
    "Gauldur Blackbow",
    "Glass Bow",
    "Glass Bow of the Stag Prince",
    "Hunting Bow",
    "Imperial Bow",
    "Karliah's Bow",
    "Long Bow",
    "Nord Hero Bow",
    "Nordic Bow",
    "Orcish Bow",
    "Stalhrim Bow",
    "Supple Ancient Nord Bow",
    "Nightingale Bow",
    "Zephyr",
    # Arrows
    "Ancient Nord Arrow",
    "Bloodcursed Elven Arrow",
    "Daedric Arrow",
    "Dragonbone Arrow",
    "Dwarven Arrow",
    "Dwarven Sphere Centurion Arrow",
    "Ebony Arrow",
    "Elven Arrow",
    "Falmer Arrow",
    "Forsworn Arrow",
    "Glass Arrow",
    "Iron Arrow",
    "Nordic Arrow",
    "Orcish Arrow",
    "Practice Arrow",
    "Riekling Spear",
    "Rusty Arrow",
    "Stalhrim Arrow",
    "Steel Arrow",
    "Sunhallowed Elven Arrow",
    # Crossbows
    "Crossbow",
    "Dwarven Crossbow",
    "Enhanced Crossbow",
    "Enhanced Dwarven Crossbow",
    # Bolts
    "Steel Bolt",
    "Dwarven Bolt",
    "Exploding Steel Bolt of Fire",
    "Exploding Steel Bolt of Ice",
    "Exploding Steel Bolt of Shock",
    "Exploding Dwarven Bolt of Fire",
    "Exploding Dwarven Bolt of Ice",
    "Exploding Dwarven Bolt of Shock",
]