# scripts/filters/jewelry.py
# Daftar nama perhiasan (jewelry) Skyrim – termasuk circlet, ring, necklace, amulet

JEWELRY_NAMES = [
    # Craftable Circlets
    "Copper and Moonstone Circlet",
    "Copper and Onyx Circlet",
    "Copper and Ruby Circlet",
    "Copper and Sapphire Circlet",
    "Gold and Emerald Circlet",
    "Gold and Ruby Circlet",
    "Jade and Emerald Circlet",
    "Jade and Sapphire Circlet",
    "Silver and Moonstone Circlet",
    "Silver and Sapphire Circlet",
    # Unique Circlets
    "Aetherial Crown",
    "Diadem of the Savant",
    "Mage's Circlet",
    "Wedding Wreath",
    # Craftable Rings
    "Gold Ring",
    "Gold Diamond Ring",
    "Gold Emerald Ring",
    "Gold Sapphire Ring",
    "Silver Ring",
    "Silver Amethyst Ring",
    "Silver Garnet Ring",
    "Silver Ruby Ring",
    # Unique Rings
    "Ahzidal's Ring of Arcana",
    "Ahzidal's Ring of Necromancy",
    "Asgeir's Wedding Band",
    "Balwen's Ornamental Ring",
    "Bone Hawk Ring",
    "Calcelmo's Ring",
    "Enchanted Ring",
    "Fjola's Wedding Band",
    "Hircine's Ring",
    "Ilas-Tei's Ring",
    "Katarina's Ornamental Ring",
    "Madesi's Silver Ring",
    "Muiri's Ring",
    "Neloth's Ring of Tracking",
    "Nightweaver's Band",
    "Pithi's Ornamental Ring",
    "Ring of Bloodlust",
    "Ring of Instinct",
    "Ring of Namira",
    "Ring of Pure Mixtures",
    "Ring of the Beast",
    "Ring of the Erudite",
    "Ring of the Hunt",
    "Ring of the Moon",
    "Silver-Blood Family Ring",
    "The Bond of Matrimony",
    "Treoy's Ornamental Ring",
    "Viola's Gold Ring",
    "Wedding Ring",
    # Craftable Necklaces
    "Gold Necklace",
    "Gold Diamond Necklace",
    "Gold Jeweled Necklace",
    "Gold Ruby Necklace",
    "Silver Necklace",
    "Silver Emerald Necklace",
    "Silver Jeweled Necklace",
    "Silver Sapphire Necklace",
    "Bone Hawk Amulet",
    # Amulets of the Nine Divines
    "Amulet of Akatosh",
    "Amulet of Arkay",
    "Amulet of Dibella",
    "Amulet of Julianos",
    "Amulet of Kynareth",
    "Amulet of Mara",
    "Amulet of Stendarr",
    "Amulet of Talos",
    "Amulet of Zenithar",
    # Unique Necklaces & Amulets
    "Amulet of Articulation",
    "Amulet of Bats",
    "Amulet of the Gargoyle",
    "Andurs' Amulet of Arkay",
    "Charmed Necklace",
    "East Empire Pendant",
    "Fjotli's Silver Locket",
    "Grosta's Necklace",
    "Jeweled Amulet",
    "Kyne's Token",
    "Locket of Saint Jiub",
    "Moon Amulet",
    "Necromancer Amulet",
    "Ogmund's Amulet of Talos",
    "Reyda's Necklace",
    "Saarthal Amulet",
    "Savos Aren's Amulet",
    "Shahvee's Amulet of Zenithar",
    "The Gauldur Amulet",
    "Yisra's Necklace",
]