# scripts/filters/keys.py
# Daftar nama kunci (keys) Skyrim – digunakan untuk filter dan proteksi proper noun

KEYS_NAMES = [
    "Abandoned Prison Key",
    "Abandoned Shack Key",
    "Aerin's House Key",
    "Angarvunde Key",
    "Ansilvund Key",
    "Arch-Mage's Quarters Key",
    "Aretino Residence Key",
    "Argonian Assemblage Key",
    "Arondil's Key",
    "Atheron Residence Key",
    "Avanchnzel Key",
    "Bee and Barb Key",
    "Belyn Hlaalu's House Key",
    "Bilegulch Mine Key",
    "Black-Briar Lodge Key",
    "Black-Briar Manor Key",
    "Black-Briar Meadery Key",
    "Bloodlet Cage Key",
    "Blue Palace Servants Key",
    "Bolli's House Key",
    "Borkul's Key",
    "Brand-Shei's Strongbox Key",
    "Brandy-Mug Farmhouse Key",
    "Brinewater Grotto Key",
    "Broken Tower Prison Key",
    "Brunwulf's House Key",
    "Cage Key",
    "Calcelmo's Laboratory Key",
    "Calixto's Key",
    "Captive Shackle Key",
    "Castle Dour Dungeon Key",
    "Cellar Key",
    "Chillrend Case Key",
    "Clan Cruel-Sea House Key",
    "Clan Shatter-Shield House Key",
    "Clan Shatter-Shield Office Key",
    "Confiscated Goods Key",
    "Cowflop Farm Key",
    "Cracked Tusk Vault Key",
    "Craglane Chest Key",
    "Craglane Dog Cage Key",
    "Crossinghouse Key",
    "Dainty Sload Footlocker Key",
    "Darklight Tower Closet Key",
    "Darklight Tower Key",
    "Darkwater Pit Key",
    "Dead Crone Rock Key",
    "Deepwood Redoubt Key",
    "Delphine's Secret Door Key",
    "Doesn't Exist",
    "Dragon Bridge Chest Key",
    "Dustman's Cairn Key",
    "Dwemer Museum Key",
    "East Empire Office Key",
    "East Empire Warehouse Key",
    "Elgrim's Elixirs Key",
    "Embershard Mine Key",
    "Faldar's Cage Key",
    "Faldar's Tooth Key",
    "Falkreath Jail Key",
    "Fellglow Keep Key",
    "Fellglow Ritual Chamber Key",
    "Fellhammer Mine Key",
    "Fellstar Farm Key",
    "Folgunthur Catacomb Key",
    "Forelhost Balcony Key",
    "Forelhost Entrance Key",
    "Forelhost Well Key",
    "Fort Blackmoor Prison Key",
    "Fort Kastav Prison Key",
    "Fort Neugrad Library Key",
    "Fort Neugrad Prison Key",
    "Fort Snowhawk Prison Key",
    "Fort Snowhawk Quarters Key",
    "Fort Sungard Jail Key",
    "Goldenglow Cellar Key",
    "Goldenglow Gate Key",
    "Goldenglow Safe Key",
    "Grelka's Market Key",
    "Habd's Lighthouse Key",
    "Haelga's Bunkhouse Key",
    "Hag Rock Ruin Jail Key",
    "Hag's End Key",
    "Hargar's Chest Key",
    "Helgen Keep Key",
    "Hillgrund's Chest Key",
    "Hillgrund's Tomb Crypt Key",
    "Hillgrund's Tomb Key",
    "Hlaalu Farmhouse Key",
    "Hollyfrost Farmhouse Key",
    "Honningbrew Brewhouse Key",
    "Honningbrew Meadery Key",
    "Horgeir's House Key",
    "Ingun's Supply Chest Key",
    "Interrogation Chamber Key",
    "Investigator's Key",
    "Irkngthand Arcanex Key",
    "Irkngthand Consortium Key",
    "Iron Key",
    "Irontree Mill House Key",
    "Japhet's Folly Key",
    "Jaree's Key",
    "Jorrvaskr Back Room Key",
    "Katariah Master Key",
    "Keerava's Key",
    "Kerah's Key",
    "Key to the Abandoned House",
    "Key to Addvar's House",
    "Key to Aeri's House",
    "Key to Aleuc's House",
    "Key to Alftand Lift",
    "Key to Alva's House",
    "Key to Alvor's House",
    "Key to Amren's House",
    "Key to Anga's Mill Common House",
    "Key to Angeline's Aromatics",
    "Key to Arcadia's Cauldron",
    "Key to Argi's Hut",
    "Key to Arnleif and Sons Trading Company",
    "Key to Bards College",
    "Key to Battle-Born Farmhouse",
    "Key to Beitild's House",
    "Key to Belethor's General Goods",
    "Key to Bits and Pieces",
    "Key to Blue Palace",
    "Key to Breezehome",
    "Key to Brina's House",
    "Key to Bryling's House",
    "Key to Bthardamz Elevator",
    "Key to Burguk's Longhouse",
    "Key to Carlotta Valentia's House",
    "Key to Castle Dour",
    "Key to Castle Dour Tower",
    "Key to Chillfurrow Farmhouse",
    "Key to Cidhna Mine",
    "Key to Corpselight Farm",
    "Key to Cosnach's Room",
    "Key to Daighre's House",
    "Key to Dawnstar Jail",
    "Key to Degaine's Room",
    "Key to Dengeir's Hall",
    "Key to Eltrys's Room",
    "Key to Endon's House",
    "Key to Enmon's House",
    "Key to Erikur's House",
    "Key to Evette San's House",
    "Key to Faendal's House",
    "Key to Falion's House",
    "Key to Fathendas House",
    "Key to Filnjar's House",
    "Key to Fruki's House",
    "Key to Garvey's Room",
    "Key to Gerdur's House",
    "Key to Gestur's House",
    "Key to Gilfre's House",
    "Key to Grave Concoctions",
    "Key to Gray Pine Goods",
    "Key to Gularz Khazgur Keep",
    "Key to Half Moon Mill",
    "Key to Halldir's Crypt",
    "Key to Halted Stream Mine",
    "Key to Heigen's Farmhouse",
    "Key to Heimskr's House",
    "Key to Hjerim",
    "Key to Hjorunn's Room",
    "Key to Honeyside",
    "Key to House Battle-Born",
    "Key to House Gray-Mane",
    "Key to House of Arkay",
    "Key to Irgnir's House",
    "Key to Jala's House",
    "Key to Jens' Farmhouse",
    "Key to Jorgen and Lami's House",
    "Key to Jorgen's Chest",
    "Key to Justiciar's Headquarter",
    "Key to Karthwasten Hall",
    "Key to Karthwasten Miners' Barracks",
    "Key to Katla's Farm",
    "Key to Kharag's Room",
    "Key to Klimmek's House",
    "Key to Kraldar's House",
    "Key to Lami's Hut",
    "Key to Larak's Longhouse",
    "Key to Left Hand Miner's Barracks",
    "Key to Leigelf's House",
    "Key to Lod's House",
    "Key to Longhouse",
    "Key to Loreius Famhouse",
    "Key to Maiden-Loom Manor",
    "Key to Margret's Room",
    "Key to Markarth Keep",
    "Key to Markarth Stables",
    "Key to Markarth Treasury House",
    "Key to Mehrunes' Shrine",
    "Key to Morthal Guardhouse",
    "Key to Morthal Jail",
    "Key to Nchuand-Zel",
    "Key to Nepos's House",
    "Key to Odfel's House",
    "Key to Ogmund's House",
    "Key to Olava the Feeble's House",
    "Key to Old Hroldan Inn",
    "Key to Omluag's Room",
    "Key to Overseer's House",
    "Key to Pavo's House",
    "Key to Pelagius Farmhouse",
    "Key to Proudspire Manor",
    "Key to Radiant Raiments",
    "Key to Ranmir's House",
    "Key to Riverwood Trader",
    "Key to Romlyn Dreth's House",
    "Key to Rustleif's House",
    "Key to Salvius Farmhouse",
    "Key to Severio Pelagia's House",
    "Key to Skaggi's House",
    "Key to Sleeping Giant Inn",
    "Key to Solitude Blacksmith",
    "Key to Solitude Cemetery",
    "Key to Solitude Fletcher",
    "Key to Solitude Lighthouse",
    "Key to Solitude Sawmill",
    "Key to Solitude Stables",
    "Key to Soljund's Miner's House",
    "Key to Sorli's House",
    "Key to Styrr's House",
    "Key to Sven's House",
    "Key to Sylgja's House",
    "Key to The Dead Man's Drink",
    "Key to the Dibella Inner Sanctum",
    "Key to the Hag's Cure",
    "Key to the Jarl's Longhouse",
    "Key to The Mortar and Pestle",
    "Key to the Nightgate Inn",
    "Key to the Silver-Blood Inn",
    "Key to the Temple of Dibella",
    "Key to the Temple of the Divines",
    "Key to the Windpeak Inn",
    "Key to Thonnir's House",
    "Key to Traillus's House",
    "Key to Ulfberth's House",
    "Key to Uthgerd the Unbroken's House",
    "Key to Vittoria Vici's House",
    "Key to Vlindrel Hall",
    "Key to Warmaiden's",
    "Key to Weylin's Room",
    "Key to Whiterun Stables",
    "Key to Winking Skeever",
    "Key to Wintersand Manor",
    "Key to Ysolda's House",
    "King Olaf's Treasury Key",
    "Kornalus Frey's Key",
    "Labyrinthian Crypt Key",
    "Lemkil's House Key",
    "Liar's Retreat Cage Key",
    "Lord Geirmund's Key",
    "Lost Knife Cage Key",
    "Lu'ah's Key",
    "Lumber Camp Key",
    "Lylvieve House Key",
    "Madanach's Key",
    "Madesi's Market Key",
    "Maluril's Room Key",
    "Mani's Cellar Key",
    "Marise's House Key",
    "Markarth Hall of the Dead Key",
    "Maven's Personal Key",
    "Mercer's House Key",
    "Mistwatch Jail Key",
    "Mistwatch Key",
    "Mithorpa's House Key",
    "Mzulft Key",
    "Mzulft Observatory Key",
    "Mzulft Room Key",
    "Nightcaller Temple Key",
    "Nightgate Inn Cellar Key",
    "Niranye's House Key",
    "Northwatch Captain's Key",
    "Northwatch Keep Key",
    "Old Solitude Crypts Key",
    "Pawned Prawn Key",
    "Pelagius Wing Key",
    "Pinewatch Key",
    "Pinewatch Treasure Room Key",
    "Potema's Catacombs Key",
    "Potema's Sanctum Key",
    "Prison Cell Key",
    "Raldbthar Key",
    "Rannveigs Fast Key",
    "Ravenscar Hallow Cage Key",
    "Red Eagle Tower Key",
    "Red Wave Safe Key",
    "Riften Fishery Key",
    "Riften Jail Key",
    "Riften North Gate Key",
    "Riften Stables Key",
    "Riften Warehouse Key",
    "Romlyn's House Key",
    "Rorik's Manor Key",
    "Sabine's Footlocker Key",
    "Sabjorn's Dresser Key",
    "Sadri's Used Wares Key",
    "Sarthis's Key",
    "Shaman's Key",
    "Shroud Hearth Barrows Key",
    "Sibbi's Chest Key",
    "Sibbi's Stash Key",
    "Silus's Museum Key",
    "Sluice Gate Key",
    "Snow-Shod House Key",
    "Syncope Sanctuary Key",
    "The Scorched Hammer Key",
    "Trap Door Key",
    "Treva's Watch Prison Key",
    "Tribute Chest Key",
    "Valindor's House Key",
    "Valthume Cellar Key",
    "Valthume Chamber Key",
    "Verner and Anneke's House Key",
    "Viola Giordano's House Key",
    "Werewolf Cage Key",
    "Whispering Door Key",
    "White Phial Key",
    "Whiterun Gate Key",
    "Whiterun Jail Key",
    "Windhelm Blacksmith Quarters Key",
    "Windhelm Jail Key",
    "Windhelm Stables Key",
]