# scripts/filters/misc.py
# Daftar nama miscellaneous items Skyrim – termasuk broken weapons, bug jars, creature parts, dragon claws, dwemer items, gems, hides, ingots, kitchenware, larceny trophies, ore, soul gems, tools, unique, dll.

MISC_NAMES = [
    # Broken weapon pieces
    "Broken Iron Mace Handle",
    "Broken Iron Mace Head",
    "Broken Iron Sword Blade",
    "Broken Iron Sword Handle",
    "Broken Iron War Axe Handle",
    "Broken Iron War Axe Head",
    "Broken Steel Battle Axe Handle",
    "Broken Steel Battle Axe Head",
    "Broken Steel Greatsword Blade",
    "Broken Steel Greatsword Handle",
    "Broken Steel Sword Blade",
    "Broken Steel Sword Handle",
    "Broken Steel Warhammer Handle",
    "Broken Steel Warhammer Head",
    # Bug jars
    "Bee in a Jar",
    "Butterfly in a Jar",
    "Dragonfly in a Jar",
    "Moth in a Jar",
    "Torchbug in a Jar",
    # Creature parts
    "Albino Spider Pod",
    "Bone Hawk Claw",
    "Bone Hawk Feathers",
    "Bone Hawk Skull",
    "Chaurus Chitin",
    "Chitin Plate",
    "Damaged Albino Spider Pod",
    "Death Hound Collar",
    "Dragon Bone",
    "Dragon Heartscales",
    "Dragon Scales",
    "Horker Tusk",
    "Mammoth Tusk",
    "Netch Leather",
    "Shellbug Chitin",
    "Skeleton Horse Leg",
    "Skull",
    "Skull (Dragonborn)",
    "Troll Skull",
    # Dragon Claws
    "Coral Dragon Claw",
    "Diamond Dragon Claw",
    "Ebony Dragon Claw",
    "Emerald Dragon Claw",
    "Glass Dragon Claw",
    "Golden Claw",
    "Iron Dragon Claw",
    "Ivory Dragon Claw",
    "Ruby Dragon Claw",
    "Sapphire Dragon Claw",
    # Dwemer items
    "Bent Dwemer Scrap Metal",
    "Centurion Dynamo Core",
    "Dwemer Bowl",
    "Dwemer Cog",
    "Dwemer Cup",
    "Dwemer Dish",
    "Dwemer Gear",
    "Dwemer Gyro",
    "Dwarven Knife",
    "Dwemer Lever",
    "Dwemer Pan",
    "Dwemer Plate",
    "Dwemer Scrap Metal",
    "Large Decorative Dwemer Strut",
    "Large Dwemer Plate Metal",
    "Large Dwemer Strut",
    "Small Dwemer Plate Metal",
    "Solid Dwemer Metal",
    # Gems
    "Amethyst",
    "Amethyst Paragon",
    "Diamond",
    "Diamond Paragon",
    "Emerald",
    "Emerald Paragon",
    "Exquisite Sapphire",
    "Flawless Amethyst",
    "Flawless Diamond",
    "Flawless Emerald",
    "Flawless Garnet",
    "Flawless Ruby",
    "Flawless Sapphire",
    "Garnet",
    "Ruby",
    "Ruby Paragon",
    "Sapphire",
    "Sapphire Paragon",
    # Hides/Pelts
    "Bear Pelt",
    "Cave Bear Pelt",
    "Cow Hide",
    "Deer Hide",
    "Deer Pelt",
    "Fox Pelt",
    "Goat Hide",
    "Horse Hide",
    "Ice Wolf Pelt",
    "Sabre Cat Pelt",
    "Sabre Cat Snow Pelt",
    "Snow Bear Pelt",
    "Snow Fox Pelt",
    "Vale Deer Hide",
    "Vale Sabre Cat Hide",
    "Werewolf Pelt",
    "Wolf Pelt",
    # Housebuilding items
    "Clay",
    "Glass",
    "Goat Horns",
    "Hinge",
    "Iron Fittings",
    "Lock",
    "Nails",
    "Quarried Stone",
    "Straw",
    # Ingots
    "Corundum Ingot",
    "Dwarven Metal Ingot",
    "Ebony Ingot",
    "Gold Ingot",
    "Iron Ingot",
    "Orichalcum Ingot",
    "Quicksilver Ingot",
    "Refined Malachite",
    "Refined Moonstone",
    "Silver Ingot",
    "Steel Ingot",
    # Kitchenware
    "Bloody Tankard",
    "Bowl",
    "Cast Iron Pot",
    "Cup",
    "Flagon",
    "Fork",
    "Goblet",
    "Kettle",
    "Knife",
    "Plate",
    "Platter",
    "Silver Goblet",
    "Silver Jug",
    "Tankard",
    "Wooden Bowl",
    "Wooden Ladle",
    "Wooden Plate",
    # Larceny trophies
    "Bust of the Gray Fox",
    "Crown of Barenziah",
    "Dwemer Puzzle Cube",
    "East Empire Shipping Map",
    "Golden Ship Model",
    "Golden Urn",
    "Honningbrew Decanter",
    "Jeweled Candlestick",
    "Jeweled Flagon",
    "Jeweled Goblet",
    "Jeweled Pitcher",
    "Left Eye of the Falmer",
    "Model Ship",
    "Ornate Drinking Horn",
    "Queen Bee Statue",
    # Ore
    "Corundum Ore",
    "Ebony Ore",
    "Gold Ore",
    "Iron Ore",
    "Malachite Ore",
    "Moonstone Ore",
    "Orichalcum Ore",
    "Quicksilver Ore",
    "Silver Ore",
    "Stalhrim",
    # Soul Gems
    "Azura's Star",
    "Black Soul Gem",
    "The Black Star",
    "Common Soul Gem",
    "Grand Soul Gem",
    "Greater Soul Gem",
    "Lesser Soul Gem",
    "Petty Soul Gem",
    "Soul Essence Gem",
    "Soul Gem Fragment",
    # Tools
    "Bellows",
    "Broom",
    "Clothes Iron",
    "Embalming Tool",
    "Fishing Pole",
    "Hammer",
    "Lockpick",
    "Pitchfork",
    "Saw",
    "Shovel",
    "Tongs",
    "Torture Tool",
    "Torture Tools",
    # Unique
    "Aetherium Crest",
    "Aetherium Shard",
    "Ancient Traveler's Skull",
    "Aretino Family Heirloom",
    "Attunement Sphere",
    "Balbus' Fork",
    "Blank Lexicon",
    "Broken Azura's Star",
    "Calcelmo's Stone Rubbing",
    "Curious Silver Mold",
    "Deathbrand Treasure Map",
    "Dragonstone",
    "Dwarven Crossbow Schematic",
    "Dwemer Exploding Fire Bolt Schematic",
    "Dwemer Exploding Ice Bolt Schematic",
    "Dwemer Exploding Shock Bolt Schematic",
    "Enhanced Crossbow Schematic",
    "Enhanced Dwarven Crossbow Schematic",
    "Essence Extractor",
    "Exquisite Sapphire",
    "Finn's Lute",
    "Focusing Crystal",
    "Gildergreen Sapling",
    "Glenmoril Witch Head",
    "Haelga's Statue of Dibella",
    "Horn of Jurgen Windcaller",
    "Imperial War Horn",
    "Klimmek's Supplies",
    "Lisbet's Dibella Statue",
    "Mammoth Tusk Powder",
    "Map of Dragon Burials",
    "Mercer's Plans",
    "Meridia's Beacon",
    "Michaela's Flagon",
    "Nurelion's Mixture",
    "Olava's Token",
    "Opaque Vessel",
    "Pelagius' Hip Bone",
    "Pest Poison",
    "Potema's Skull",
    "Quill of Gemination",
    "Reaper Gem Fragment",
    "Rjorn's Drum",
    "Roasted Ox Head",
    "Roasted Ox Leg",
    "Right Eye of the Falmer",
    "Runed Lexicon",
    "Saerek's Skull Key",
    "Torsten's Skull Key",
    "Satchel of Moon Sugar",
    "Sealed Scroll",
    "Sigil Stone",
    "Silver Candlestick",
    "Silver Hand Stratagem",
    "Sinding's Skin",
    "Sylgja's Satchel",
    "The Dancer's Flute",
    "Tolfdir's Alembic",
    "Torc of Labyrinthian",
    "Torygg's War Horn",
    "Verner's Satchel",
    "Warped Soul Gem",
    "Wedding Ring",
    "Werewolf Totem",
    "Wylandriah's Soul Gem",
    "Wylandriah's Spoon",
    "Ysgramor's Soup Spoon",
    # Other
    "Basket",
    "Bucket",
    "Bloody Rags",
    "Burned Book",
    "Candlestick",
    "Charcoal",
    "Child's Doll",
    "Dibella Statue",
    "Do Not Delete",
    "Drum",
    "Empty Skooma Bottle",
    "Empty Wine Bottle",
    "Firewood",
    "Flag",
    "Flower Basket",
    "Flute",
    "Heart Stone",
    "Inkwell",
    "Jug",
    "Kagrumez Resonance Gem",
    "Lantern",
    "Leather",
    "Leather Strips",
    "Linen Wrap",
    "Lute",
    "Pot",
    "Quill",
    "Roll of Paper",
    "Ruined Book",
    "Silver Candlestick",
    "Soaked Taproot",
    "Spigot",
    "Stones of Barenziah",
    "Torch",
    "Vampire Doll",
]