# scripts/filters/npc.py
# Daftar nama NPC Skyrim – digunakan untuk filter dan proteksi proper noun

NPC_NAMES = [
    "Adrianne Avenicci",
    "Aduri Sarethi",
    "Aerin",
    "Ahlam",
    "Aia Arria",
    "Aicantar",
    "Alessandra",
    "Alexia Vici",
    "Alfhild Battle-Born",
    "Alva",
    "Angeline Morrard",
    "Angi",
    "Annekke Crag-Jumper",
    "Anoriath",
    "Anska",
    "Anuriel",
    "Anwen",
    "Arcadia",
    "Arivanya",
    "Arvel the Swift",
    "Avrusa Sarethi",
    "Fjola",
    "Beitild",
    "Bergritte Battle-Born",
    "Betrid Silver-Blood",
    "Birna",
    "Bothela",
    "Boti",
    "Braig",
    "Brelas",
    "Brina Merilis",
    "Bryling",
    "Camilla Valerius",
    "Carlotta Valentia",
    "Constance Michel",
    "Corpulus Vinius",
    "Cosnach",
    "Curwe",
    "Danica Pure-Spring",
    "Dinya",
    "Dorian",
    "Drifa",
    "Duach",
    "Eisa Blackthorn",
    "Elda",
    "Elisif the Fair",
    "Elrindir",
    "Eltrys",
    "Endarie",
    "Eola",
    "Erandur",
    "Erik and Erik the Slayer",
    "Eris",
    "Evette San",
    "Faendal",
    "Faida",
    "Faleen",
    "Fastred",
    "Frabbi",
    "Fralia Gray-Mane",
    "Freir",
    "Frida",
    "Frightened Woman",
    "Gerdur",
    "Gisli",
    "Golldir",
    "Grelka",
    "Grelod the Kind",
    "Greta",
    "Gwilin",
    "Haelga",
    "Hamal",
    "Haran",
    "Hemming Black-Briar",
    "Hillevi Cruel-Sea",
    "Hroki",
    "Hulda",
    "Idesa Sadri",
    "Idgrod Ravencrone",
    "Idgrod the Younger",
    "Illdi",
    "Illia",
    "Imedhnain",
    "Indaryn",
    "Inge Six Fingers",
    "Ingun Black-Briar",
    "Irileth",
    "Isabelle Rolaine",
    "Jala",
    "Jenassa",
    "Jonna",
    "Julienne Lylvieve",
    "Karita",
    "Katla",
    "Keeper Carcette",
    "Kerah",
    "Laila Law-Giver",
    "Lami",
    "Lisbet",
    "Lisette",
    "Luaffyn",
    "Lydia",
    "Lynly Star-Sung",
    "Madena",
    "Margret",
    "Marise Aravel",
    "Maurice Jondrelle",
    "Maven Black-Briar",
    "Medresi Dran",
    "Michel Lylvieve",
    "Mjoll the Lioness",
    "Muiri",
    "Narri",
    "Nenya",
    "Nilsine Shatter-Shield",
    "Niluva Hlaalu",
    "Nimphaneth",
    "Niranye",
    "Nura Snow-Shod",
    "Nurelion",
    "Odvan",
    "Olava the Feeble",
    "Olda",
    "Olfina Gray-Mane",
    "Orla",
    "Pantea Ateia",
    "Perth",
    "Quintus Navale",
    "Reldith",
    "Revyn Sadri",
    "Rhiada",
    "Romlyn Dreth",
    "Saadia",
    "Sabine Nytte",
    "Safia",
    "Salma",
    "Senna",
    "Seren",
    "Sibbi Black-Briar",
    "Sigrid",
    "Silana Petreia",
    "Silda the Unseen",
    "Sondas Drenim",
    "Sorex Vinius",
    "Susanna the Wicked",
    "Suvaris Atheron",
    "Svana Far-Shield",
    "Sven",
    "Sybille Stentor",
    "Sylgja",
    "Taarie",
    "Talsgar the Wanderer",
    "Tekla",
    "Temba Wide-Arm",
    "Tilma the Haggard",
    "Tormir",
    "Tova Shatter-Shield",
    "Tythis Ulen",
    "Uaile",
    "Ungrien",
    "Uraccen",
    "Uthgerd the Unbroken",
    "Valdr",
    "Valga Vinicia",
    "Valindor",
    "Velehk Sain",
    "Viola Giordano",
    "Vittoria Vici",
    "Vivienne Onis",
    "Voada",
    "Wylandriah",
    "Ysolda",
    "Zaria",
    "Unnamed female Imperial hunter at the hotspring near Eldergleam",
    "Unnamed female Redguard hunter at the hotspring",
    "Unnamed male Nord hunter at the hotspring",
    "Abelone",
    "Adelaisa Avenicci",
    "Aeri",
    "Agnis",
    "Aranea Ilenith",
    "Bodil",
    "Dravynea the Stoneweaver",
    "Edith",
    "Erdi",
    "Eydis",
    "Ganna Uriel",
    "Gemma Uriel",
    "Gormlaith Golden-Hilt",
    "Hermir Strong-Heart",
    "Hert",
    "Hilde",
    "Iddra",
    "Indara Caerelia",
    "Irgnir",
    "Jora",
    "Kaie",
    "Lu'ah al-Skaven",
    "Ondolemar",
    "Saffir",
    "Salonia Carvain",
    "Sorli the Builder",
    "Thaena",
    "Una",
    "Voldsea Giryon",
    "Adisla",
    "Ainethach",
    "Ambarys Rendar",
    "Bolfrida Brandy-Mug",
    "Fruki",
    "Gilfre",
    "Grosta",
    "Hafjorg",
    "Iona",
    "Jordis the Shield-Maiden",
    "Lynea",
    "Malthyr Elenil",
    "Mena",
    "Nana Ildene",
    "Nimriel",
    "Viriya",
    "Alvor",
    "Aringoth",
    "Asta",
    "Cairine",
    "Daighre",
    "Edda",
    "Fianna",
    "Fridrika",
    "Gerda",
    "Gwendolyn",
    "Helgird",
    "Karita the Pilgrim",
    "Leonara Arius",
    "Sosia Tremellia",
    "Swanhvir",
    "Synda Llanith",
    "Tuthul",
    "Umana",
    "Vald",
    "Vigdis Salvius",
    "Adril Arano",
    "Aphia Velothi",
    "Bralsa Drel",
    "Cindiri Arano",
    "Crescius Carellius",
    "Dreyla Alor",
    "Drovas Relvi",
    "Falx Caerellius",
    "Fanari Strong-Voice",
    "Fethis Alor",
    "Frea",
    "Garyn Ienth",
    "Geldis",
    "Milore Ienth",
    "Mirri Severin",
    "Councilor Lleril Morvayn",
    "Ralis Sedarys",
    "Rirns Llervu",
    "Slitter",
    "Talvas Fathryon",
    "Teldryn Sero",
    "Tilisu Severin",
    "Varona",
    "Captain Veleth",
    "Vendil Severin",
    "Bujold the Intrepid",
    "Edla",
    "Elynea Mothren",
    "Finna",
    "Hilund",
    "Morwen",
    "Yrsa",
    "Beleval",
    "Tilde",
    "Vori",
    "Fura Bloodmouth",
    "Hestla",
    "Ingjard",
    "Modhna",
    "Salonia Caelia",
    "Sorine Jurard",
    "Lillith Maiden-Loom",
    "Katria",
    "Hjordis",
    "Rakel",
    "Arch-Curate Vyrthur",
    "Knight-Paladin Gelebor",
    "Mirabelle Ervine",
    "Faralda",
    "Nirya",
    "Brelyna Maryon",
    "Onmund",
    "Enthir",
    "Talib",
    "Elgrim",
    "Dravin Llenith",
    "Aspiring Mage",
    "Galathil",
    "Herkja",
    "Faldrus",
    "Sigar",
    "Ardwen",
    "Anise",
    "Colette Marence",
    "Orthorn",
    "The Caller",
    "Farmer",
    "Farmer",
    "Farmer",
    "Grisvar the Unlucky",
    "Argi Farseer",
    "Threki the Innocent",
    "Bjartur",
    "Domna Magia",
    "Redguard Woman",
    "Alain Dufont",
    "Alea Quintus",
    "Breya",
    "Drennen",
    "Syndus",
    "Vanryth Gatharian",
    "Willem",
    "Ennoc",
    "Ennodius Papius",
    "Belyn Hlaalu",
    "Revus Sarvani",
    "Ulves Romoran",
    "Elder Othreloth",
    "Galdrus Hlervu",
    "Rayya",
    "Sonir",
    "Oriella",
    "Ildari Sathrothil",
    "Niyya",
    "Akar",
    "Majni",
    "Ancarion",
    "Heroes of Sovngarde",
    "Ingrid",
    "Matlara",
    "Imperial Captain",
    "Imperial Archer",
    "Stormcloak Soldiers",
    "Imperial Priestess",
    "Jayri",
    "Alvide",
    "Laelette the Vampire",
    "Minorne",
    "Agna",
    "Gianna",
    "Hefid the Deaf",
    "Madwoman",
    "Sultry Maiden",
    "Dealer",
    "Lurbuk",
    "Chief Mauhulakh",
    "Urag gro-Shub",
    "Chief Yamarz",
    "Lash gra-Dushnikh",
    "Sharamph",
    "Arob",
    "Gharol",
    "Chief Burguk",
    "Ghorbash the Iron Hand",
    "Balagog gro-Nolob",
    "Moth gro-Bagol",
    "Mulush gro-Shugurz",
    "Urzoga gra-Shugurz",
    "Ghorza gra-Bagol",
    "Murbul",
    "Borgakh the Steel Heart",
    "Shel",
    "Peddler",
    "Peddler",
    "Grete",
    "Sickly Farmer",
    "Bolar",
    "Yatul",
    "Urog",
    "Dushnamub",
    "Sulla Trebatius",
    "Captain Valmir",
    "Umurn",
    "Nagrub",
    "Oglub",
    "Torture Victim",
    "Torture Victim",
    "Ugor",
    "Garakh",
    "Lob",
    "Atub",
    "Gularzob",
    "Vals Veran",
    "Borkul the Beast",
    "Chief Larak",
    "Bagrak",
    "Shuftharz",
    "Gadba gro-Largash",
    "Mul gro-Largash",
    "Ogol",
    "Malyn Varen",
    "Sarthis Idren",
    "Orini Dral",
    "Grogmar gro-Burzog",
    "Gat gro-Shargakh",
    "Champion of Boethiah",
    "Olur",
    "Louis Letrush",
    "Old Orc",
    "Taron Dreth",
    "Malkus",
    "Saliah",
    "Mogrul",
    "Celann",
    "Ronthil",
    "Garan Marethi",
    "Vingalmo",
    "Ancano",
    "Drevis Neloren",
    "Nelacar",
    "Feran Sadri",
    "Orthjolf",
    "Rargal Thrallmaster",
    "Namasur",
    "Yag gra-Gortwog",
    "Valie",
    "Endrast",
    "Neloth",
    "Vorstag",
    "Lucan Valerius",
    "Orgnar",
    "Rexus",
    "Sinding",
    "Aspect of Hircine",
    "Savos Aren",
    "Tolfdir",
    "Benor",
    "Kjeld the Younger",
    "Stenvar",
    "Asbjorn Fire-Tamer",
    "Asgeir Snow-Shod",
    "Balimund",
    "Brand-Shei",
    "Orthus Endario",
    "Torbjorn Shatter-Shield",
    "Faryl Atheron",
    "Captain Lonely-Gale",
    "Torsten Cruel-Sea",
    "Aval Atheron",
    "Ulundil",
]