# scripts/filters/potions.py
# Daftar nama ramuan (potions) dan racun (poisons) Skyrim

POTIONS_NAMES = [
    # Cure
    "Potion of Cure Disease",
    "Potion of Cure Poison",
    # Fortify Alteration
    "Potion of Alteration",
    "Draught of Alteration",
    "Philter of Alteration",
    "Elixir of Alteration",
    # Fortify Barter
    "Potion of Haggling",
    "Draught of Haggling",
    "Philter of Haggling",
    "Elixir of Haggling",
    # Fortify Blocking
    "Potions of the Defender",
    "Draught of the Defender",
    "Philter of the Defender",
    "Elixir of the Defender",
    # Fortify Carry Weight
    "Potion of Strength",
    "Draught of Strength",
    "Solution of Strength",
    "Philter of Strength",
    "Elixir of Strength",
    # Fortify Conjuration
    "Conjurer's Potion",
    "Conjurer's Draught",
    "Conjurer's Philter",
    "Conjurer's Elixir",
    # Fortify Destruction
    "Potion of Destruction",
    "Draught of Destruction",
    "Philter of Destruction",
    "Elixir of Destruction",
    # Fortify Enchanting
    "Enchanter's Potion",
    "Enchanter's Draught",
    "Enchanter's Philter",
    "Enchanter's Elixir",
    # Fortify Health
    "Potion of Health",
    "Draught of Health",
    "Solution of Health",
    "Philter of Health",
    "Elixir of Health",
    # Fortify Heavy Armor
    "Potion of the Knight",
    "Draught of the Knight",
    "Philter of the Knight",
    "Elixir of the Knight",
    # Fortify Illusion
    "Potion of Illusion",
    "Draught of Illusion",
    "Philter of Illusion",
    "Elixir of Illusion",
    # Fortify Light Armor
    "Skirmisher's Potion",
    "Skirmisher's Draught",
    "Skirmisher's Philter",
    "Skirmisher's Elixir",
    # Fortify Lockpicking
    "Potion of Lockpicking",
    "Draught of Lockpicking",
    "Philter of Lockpicking",
    "Elixir of Lockpicking",
    # Fortify Magicka
    "Potion of Extra Magicka",
    "Draught of Extra Magicka",
    "Solution of Extra Magicka",
    "Philter of Extra Magicka",
    "Elixir of Extra Magicka",
    # Fortify Marksman
    "Potion of True Shot",
    "Draught of True Shot",
    "Philter of True Shot",
    "Elixir of True Shot",
    # Fortify One-Handed
    "Potion of the Warrior",
    "Draught of the Warrior",
    "Philter of the Warrior",
    "Elixir of the Warrior",
    # Fortify Pickpocket
    "Potion of Pickpocketing",
    "Draught of Pickpocketing",
    "Philter of Pickpocketing",
    "Elixir of Pickpocketing",
    # Fortify Restoration
    "Potion of the Healer",
    "Draught of the Healer",
    "Philter of the Healer",
    "Elixir of the Healer",
    # Fortify Smithing
    "Blacksmith's Potion",
    "Blacksmith's Draught",
    "Blacksmith's Philter",
    "Blacksmith's Elixir",
    # Fortify Sneak
    "Potion of Light Feet",
    "Draught of Light Feet",
    "Philter of Light Feet",
    "Elixir of Light Feet",
    # Fortify Persuasion
    "Potion of Glibness",
    "Draught of Glibness",
    "Philter of Glibness",
    "Elixir of Glibness",
    # Fortify Stamina
    "Potion of Enhanced Stamina",
    "Draught of Enhanced Stamina",
    "Solution of Enhanced Stamina",
    "Philter of Enhanced Stamina",
    "Elixir of Enhanced Stamina",
    # Fortify Two-Handed
    "Potion of the Berserker",
    "Draught of the Berserker",
    "Philter of the Berserker",
    "Elixir of the Berserker",
    # Invisibility
    "Potion of Brief Invisibility",
    "Potion of Extended Invisibility",
    "Potion of Enduring Invisibility",
    "Potion of Prolonged Invisibility",
    # Regenerate Health
    "Potion of Regeneration",
    "Draught of Regeneration",
    "Solution of Regeneration",
    "Philter of Regeneration",
    "Elixir of Regeneration",
    # Regenerate Magicka
    "Potion of Lasting Potency",
    "Draught of Lasting Potency",
    "Solution of Lasting Potency",
    "Philter of Lasting Potency",
    "Elixir of Lasting Potency",
    # Regenerate Stamina
    "Potion of Vigor",
    "Draught of Vigor",
    "Solution of Vigor",
    "Philter of Vigor",
    "Elixir of Vigor",
    # Resist Fire
    "Potion of Resist Fire",
    "Draught of Resist Fire",
    "Philter of Resist Fire",
    "Elixir of Resist Fire",
    # Resist Frost
    "Potion of Resist Cold",
    "Draught of Resist Cold",
    "Philter of Resist Cold",
    "Elixir of Resist Cold",
    # Resist Magic
    "Potion of Resist Magic",
    "Draught of Resist Magic",
    "Philter of Resist Magic",
    "Elixir of Resist Magic",
    # Resist Shock
    "Potion of Resist Shock",
    "Draught of Resist Shock",
    "Philter of Resist Shock",
    "Elixir of Resist Shock",
    # Restore Health
    "Potion of Minor Healing",
    "Potion of Healing",
    "Potion of Plentiful Healing",
    "Potion of Vigorous Healing",
    "Potion of Extreme Healing",
    "Potion of Ultimate Healing",
    # Restore Magicka
    "Potion of Minor Magicka",
    "Potion of Magicka",
    "Potion of Plentiful Magicka",
    "Potion of Vigorous Magicka",
    "Potion of Extreme Magicka",
    "Potion of Ultimate Magicka",
    # Restore Stamina
    "Potion of Minor Stamina",
    "Potion of Stamina",
    "Potion of Plentiful Stamina",
    "Potion of Vigorous Stamina",
    "Potion of Extreme Stamina",
    "Potion of Ultimate Stamina",
    # Waterbreathing
    "Potion of Waterbreathing",
    "Draught of Waterbreathing",
    "Philter of Waterbreathing",
    "Elixir of Waterbreathing",
    # Waterwalking
    "Potion of Waterwalking",
    # Well-being
    "Potion of Minor Well-being",
    "Potion of Well-being",
    "Potion of Plentiful Well-being",
    "Potion of Vigorous Well-being",
    "Potion of Extreme Well-being",
    "Potion of Ultimate Well-being",
    # Thieves Guild - Plunder
    "Potion of Plunder",
    "Draught of Plunder",
    "Philter of Plunder",
    "Elixir of Plunder",
    "Grand Elixir of Plunder",
    "Prime Elixir of Plunder",
    # Thieves Guild - Conflict
    "Potion of Conflict",
    "Draught of Conflict",
    "Philter of Conflict",
    "Elixer of Conflict",  # ejaan asli
    "Grand Elixer of Conflict",
    "Prime Elixir of Conflict",
    # Thieves Guild - Larceny
    "Potion of Larceny",
    "Draught of Larceny",
    "Philter of Larceny",
    "Elixir of Larceny",
    "Grand Elixir of Larceny",
    "Prime Elixir of Larceny",
    # Thieves Guild - Keenshot
    "Potion of Keenshot",
    "Draught of Keenshot",
    "Philter of Keenshot",
    "Elixir of Keenshot",
    "Grand Elixir of Keenshot",
    "Prime Elixir of Keenshot",
    # Thieves Guild - Escape
    "Potion of Escape",
    "Draught of Escape",
    "Philter of Escape",
    "Elixir of Escape",
    "Grand Elixir of Escape",
    "Prime Elixir of Escape",
    # Unique potions
    "Cliff Racer",
    "Esbern's Potion",
    "Falmer Blood Elixir",
    "Ice Wraith Essence",
    "Philter of the Phantom",
    "Potion of Blood",
    "Soul Husk Extract",
    "Vaermina's Torpor",
    "Velvet LeChance",
    "White-Gold Tower",
    "White Phial",
    # Drugs
    "Redwater Skooma",
    "Skooma",
    "Sleeping Tree Sap",
    # Poisons - Damage Health
    "Weak Poison",
    "Poison",
    "Potent Poison",
    "Virulent Poison",
    "Deadly Poison",
    # Poisons - Damage Magicka
    "Weak Magicka Poison",
    "Magicka Poison",
    "Potent Magicka Poison",
    "Malign Magicka Poison",
    "Deadly Magicka Poison",
    # Poisons - Damage Magicka Regen
    "Weak Recovery Poison",
    "Magicka Recovery Poison",
    "Potent Recovery Poison",
    "Malign Recovery Poison",
    "Deadly Recovery Poison",
    # Poisons - Damage Stamina
    "Weak Stamina Poison",
    "Stamina Poison",
    "Potent Stamina Poison",
    "Virulent Stamina Poison",
    "Deadly Stamina Poison",
    # Poisons - Damage Stamina Regen
    "Weak Vigor Poison",
    "Vigor Poison",
    "Potent Vigor Poison",
    "Malign Vigor Poison",
    # Poisons - Fear
    "Weak Fear Poison",
    "Fear Poison",
    "Potent Fear Poison",
    "Virulent Fear Poison",
    "Deadly Fear Poison",
    # Poisons - Frenzy
    "Weak Frenzy Poison",
    "Frenzy Poison",
    "Potent Frenzy Poison",
    "Virulent Frenzy Poison",
    "Deadly Frenzy Poison",
    # Poisons - Lingering Damage Health
    "Weak Lingering Poison",
    "Lingering Poison",
    "Potent Lingering Poison",
    "Malign Lingering Poison",
    "Deadly Lingering Poison",
    # Poisons - Lingering Damage Magicka
    "Lingering Magicka Poison",
    "Enduring Magicka Poison",
    "Lasting Magicka Poison",
    "Persisting Magicka Poison",
    "Unceasing Magicka Poison",
    # Poisons - Lingering Damage Stamina
    "Lingering Stamina Poison",
    "Enduring Stamina Poison",
    "Lasting Stamina Poison",
    "Persistent Stamina Poison",
    "Unceasing Stamina Poison",
    # Poisons - Paralysis
    "Weak Paralysis Poison",
    "Paralysis Poison",
    "Potent Paralysis Poison",
    "Virulent Paralysis Poison",
    "Deadly Paralysis Poison",
    # Poisons - Weakness to Fire
    "Weak Aversion to Fire",
    "Aversion to Fire",
    "Potent Aversion to Fire",
    "Malign Aversion to Fire",
    "Deadly Aversion to Fire",
    # Poisons - Weakness to Frost
    "Weak Aversion to Frost",
    "Aversion to Frost",
    "Potent Aversion to Frost",
    "Malign Aversion to Frost",
    "Deadly Aversion to Frost",
    # Poisons - Weakness to Magic
    "Weak Aversion to Magic",
    "Aversion to Magic",
    "Potent Aversion to Magic",
    "Malign Aversion to Magic",
    "Deadly Aversion to Magic",
    # Poisons - Weakness to Shock
    "Weak Aversion to Shock",
    "Aversion to Shock",
    "Potent Aversion to Shock",
    "Malign Aversion to Shock",
    "Deadly Aversion to Shock",
    # Unique poisons
    "Nightshade Extact",  # ejaan asli
    "Frostbite Venom",
    "Lotus Extract",
    "Ice Wraith Bane",
]