# scripts/filters/quest_items.py
# Daftar nama item quest (quest items) Skyrim – digunakan untuk filter dan proteksi proper noun

QUEST_ITEMS_NAMES = [
    "Aela's Shield",
    "Alessandra's Dagger",
    "Alethius's Notes",
    "Alto Wine",
    "Amaund Motierre's Sealed Letter",
    "Amren's Family Sword",
    "Annals of the Dragonguard",
    "Andurs' Amulet of Arkay",
    "Argonian Ale",
    "Attunement Sphere",
    "Balgruuf's Greatsword",
    "Balgruuf's War Axe",
    "Balmora Blue",
    "Balwen's Ornamental Ring",
    "Black-Briar Mead Keg",
    "Blade of Sacrifice",
    "Blank Lexicon",
    "Briar Heart",
    "Broken Azura's Star",
    "Bust of the Gray Fox",
    "Calcelmo's Stone Rubbing",
    "Ceremonial Axe",
    "Ceremonial Sword",
    "Colovian Brandy",
    "White Phial",
    "Crown of Barenziah",
    "Curious Silver Mold",
    "Dibella Statue",
    "Double-Distilled Skooma",
    "Dragon's Breath Mead",
    "Dragonstone",
    "Dragon Heartscales",
    "Dravin's Bow",
    "Dwemer Cog",
    "Dwemer Puzzle Cube",
    "East Empire Shipping Map",
    "Eldergleam Sap",
    "Eldergleam Sapling",
    "Elder Scroll",
    "Essence Extractor",
    "Erj's Notes",
    "Fine-Cut Void Salts",
    "Finn's Lute",
    "Firebrand Wine Case",
    "Fjola's Wedding Band",
    "Fjotli's Silver Locket",
    "Focusing Crystal",
    "Fragment of Wuuthrad",
    "Fragments of Wuuthrad",
    "Frost's Identity Papers",
    "Gauldur Amulet Fragment",
    "Glenmoril Witch Head",
    "Golden Claw",
    "Golden Ship Model",
    "Golden Urn",
    "Grimsever",
    "Habd's Remains",
    "Harrald's Sword",
    "Heddic's Volunruud Notes",
    "Helm of Winterhold",
    "Hilt of Mehrunes' Razor",
    "Hjalti's Sword",
    "Honningbrew Decanter",
    "Horn of Jurgen Windcaller",
    "Hrolfdir's Shield",
    "Idgrod's Note",
    "Imperial Documents",
    "Iron Dragon Claw",
    "Jarrin Root",
    "Jessica's Wine",
    "Jeweled Amulet",
    "Jeweled Flagon",
    "Jeweled Goblet",
    "Jeweled Pitcher",
    "Kahvozein's Fang",
    "Katarina's Ornamental Ring",
    "Klimmek's Supplies",
    "Krag's Journal",
    "Left Eye of the Falmer",
    "Letter from Falk Firebeard",
    "Lexicon",
    "Lisbet's Dibella Statue",
    "Madesi's Silver Ring",
    "Mammoth Tusk Powder",
    "Mark of Dibella",
    "Meridia's Beacon",
    "Model Ship",
    "Necromancer Amulet",
    "Nettlebane",
    "Nightshade Extact",
    "Noster's Helmet",
    "Olava's Token",
    "Onmund's Amulet",
    "Ornate Drinking Horn",
    "Pelagius' Hip Bone",
    "Pantea's Flute",
    "Pithi's Ornamental Ring",
    "Pommel Stone of Mehrunes' Razor",
    "Potema's Skull",
    "Queen Bee Statue",
    "Queen Freydis's Sword",
    "Quill of Gemination",
    "Ring of Pure Mixtures",
    "Rogatus's Letter",
    "Roggi's Ancestral Shield",
    "Runil's Journal",
    "Rjorn's Drum",
    "Saerek's Skull Key",
    "Satchel of Moon Sugar",
    "Scabbard of Mehrunes' Razor",
    "Sealed Scroll",
    "Shards of Mehrunes' Razor",
    "Shahvee's Amulet of Zenithar",
    "Sigil Stone",
    "Silver Candlestick",
    "Silver Hand Stratagem",
    "Sinding's Skin",
    "Skeleton Key",
    "Skooma",
    "Spiced Beef",
    "Staff of Magnus",
    "Stallion's Potion",
    "Stormcloak Documents",
    "Strange Amulet",
    "Stros M'Kai Rum",
    "The Black Star",
    "The Bond of Matrimony",
    "Tolfdir's Alembic",
    "Torc of Labyrinthian",
    "Torsten's Skull Key",
    "Torygg's War Horn",
    "Treoy's Ornamental Ring",
    "Ulfric's War Axe",
    "Unmelting Snow",
    "Unusual Gem",
    "Vilkas's Sword",
    "Warped Soul Gem",
    "Wedding Ring",
    "Werewolf Totem",
    "Wuuthrad",
    "Wylandriah's Spoon",
    "Wyndelius's Journal",
]