# scripts/filters/scrolls.py
# Daftar nama gulungan (scrolls) Skyrim – termasuk Alteration, Conjuration, Destruction, Illusion, Restoration, dan Spider scrolls

SCROLLS_NAMES = [
    # Alteration
    "Scroll of Candlelight",
    "Scroll of Detect Life",
    "Scroll of Dragonhide",
    "Scroll of Ebonyflesh",
    "Scroll of Ironflesh",
    "Scroll of Magelight",
    "Scroll of Mass Paralysis",
    "Scroll of Oakflesh",
    "Scroll of Paralyze",
    "Scroll of Stoneflesh",
    "Scroll of Waterbreathing",
    # Conjuration
    "Scroll of Banish Daedra",
    "Scroll of Command Daedra",
    "Scroll of Conjure Familiar",
    "Scroll of Conjure Flame Atronach",
    "Scroll of Conjure Frost Atronach",
    "Scroll of Conjure Storm Atronach",
    "Scroll of Dead Thrall",
    "Scroll of Dread Zombie",
    "Scroll of Expel Daedra",
    "Scroll of Flame Thrall",
    "Scroll of Frost Thrall",
    "Scroll of Raise Zombie",
    "Scroll of Reanimate Corpse",
    "Scroll of Revenant",
    "Scroll of Soul Trap",
    "Scroll of Storm Thrall",
    # Destruction
    "J'zargo's Flame Cloak Scroll",
    "Scroll of Blizzard",
    "Scroll of Chain Lightning",
    "Scroll of Fire Rune",
    "Scroll of Fire Storm",
    "Scroll of Fireball",
    "Scroll of Firebolt",
    "Scroll of Flame Cloak",
    "Scroll of Frost Cloak",
    "Scroll of Frost Rune",
    "Scroll of Ice Spike",
    "Scroll of Ice Storm",
    "Scroll of Lightning Bolt",
    "Scroll of Lightning Cloak",
    "Scroll of Lightning Rune",
    # Illusion
    "Scroll of Call to Arms",
    "Scroll of Calm",
    "Scroll of Courage",
    "Scroll of Fear",
    "Scroll of Frenzy",
    "Scroll of Fury",
    "Scroll of Harmony",
    "Scroll of Hysteria",
    "Scroll of Invisibility",
    "Scroll of Mayhem",
    "Scroll of Muffle",
    "Scroll of Pacify",
    "Scroll of Rally",
    "Scroll of Rout",
    # Restoration
    "Scroll of Bane of the Undead",
    "Scroll of Circle of Protection",
    "Scroll of Cure Wounds",
    "Scroll of Fast Healing",
    "Scroll of Grand Healing",
    "Scroll of Guardian Circle",
    "Scroll of Heal Other",
    "Scroll of Repel Lesser Undead",
    "Scroll of Repel Undead",
    "Scroll of Turn Greater Undead",
    "Scroll of Turn Lesser Undead",
    "Scroll of Turn Undead",
    # Other (Shalidor's Insights)
    "Shalidor's Insights: Alteration",
    "Shalidor's Insights: Conjuration",
    "Shalidor's Insights: Destruction",
    "Shalidor's Insights: Illusion",
    "Shalidor's Insights: Magicka",
    "Shalidor's Insights: Restoration",
    # Spider Scrolls (Dragonborn DLC)
    "Exploding Flame Spider",
    "Exploding Frost Spider",
    "Exploding Poison Spider",
    "Exploding Shock Spider",
    "Flame Cloaked Spider",
    "Frost Cloaked Spider",
    "Glowing Spider",
    "Jumping Flame Spider",
    "Jumping Frost Spider",
    "Jumping Poison Spider",
    "Jumping Shock Spider",
    "Mind Control Spider",
    "Oil Spider",
    "Pack Spider",
    "Poison Cloaked Spider",
    "Shock Cloaked Spider",
]