# scripts/filters/shields.py
# Daftar nama perisai (shields) Skyrim – termasuk light, heavy, unique, dan hold guard

SHIELDS_NAMES = [
    # Light Shields
    "Amber Shield",
    "Chitin Shield",
    "Dark Seducer Shield",
    "Dragonscale Shield",
    "Elven Shield",
    "Glass Shield",
    "Hide Shield",
    "Imperial Light Shield",
    "Netch Leather Shield",
    "Netch Leather Tower Shield",
    "Remnant Shield",
    "Shadowed Netch Leather Shield",
    "Shadowed Netch Leather Tower Shield",
    "Stalhrim Shield",
    # Heavy Shields
    "Banded Iron Shield",
    "Blades Ebony Shield",
    "Blades Shield",
    "Bonemold Shield",
    "Daedric Shield",
    "Dawnguard Shield",
    "Dented Iron Shield",
    "Dragonplate Shield",
    "Dwarven Shield",
    "Ebony Shield",
    "Falmer Shield",
    "Golden Saint Shield",
    "Hrolfdir's Shield",
    "Imperial Dragon Shield",
    "Imperial Shield",
    "Improved Bonemold Shield",
    "Iron Shield",
    "Madness Shield",
    "Nordic Shield",
    "Orcish Shield",
    "Ordinator Shield",
    "Roggi's Ancestral Shield",
    "Skull-Sabre Shield",
    "Steel Shield",
    # Unique Shields
    "Aela's Shield",
    "Aetherial Shield",
    "Auriel's Shield",
    "Dawnguard Rune Shield",
    "Herebane's Fortress",
    "Reflecting Shield",
    "Shield of Solitude",
    "Shield of Ysgramor",
    "Spellbreaker",
    "Targe of the Blooded",
    # Hold Guard Shields
    "Falkreath Guard's Shield",
    "Hjaalmarch Guard's Shield",
    "Markarth Guard's Shield",
    "Pale Guard's Shield",
    "Riften Guard's Shield",
    "Solitude Guard's Shield",
    "Whiterun Guard's Shield",
    "Windhelm Guard's Shield",
    "Winterhold Guard's Shield",
]